(async()=>{
const R=[];const ok=(name,cond,info)=>R.push((cond?'PASS ':'FAIL ')+name+(info!==undefined?' :: '+info:''));
const wait=ms=>new Promise(r=>setTimeout(r,ms));const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const click=el=>{if(!el)throw new Error('missing element');el.click();};
const ptr=(type,x,y,target)=>(target||window).dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,clientX:x,clientY:y,button:0,buttons:type==='pointerup'?0:1,pointerType:'mouse',isPrimary:true}));
const center=el=>{const r=el.getBoundingClientRect();return [r.left+r.width/2,r.top+Math.min(r.height/2,30)];};
const freePoint=cell=>{const r=cell.getBoundingClientRect(),x=r.left+r.width/2;for(let y=Math.min(r.bottom-4,innerHeight-70);y>r.top;y-=8){const el=document.elementFromPoint(x,y);if(el&&el.closest('.wk-cell')===cell&&!el.closest('.cc'))return [x,y];}return [x,r.top+4];};
const dragTo=async(src,target,isCell)=>{src.scrollIntoView({block:'center'});await wait(30);const [x0,y0]=center(src);ptr('pointerdown',x0,y0,src);ptr('pointermove',x0+12,y0+8);const p=isCell?freePoint(target):center(target);ptr('pointermove',p[0],p[1]);return p;};
const setSel=(id,v)=>{const s=$(id);s.value=v;s.dispatchEvent(new Event('change',{bubbles:true}));};
const typeIn=(id,v)=>{const i=$(id);i.value=v;i.dispatchEvent(new Event('input',{bubbles:true}));};
const store=()=>[...window.__store.entries()];
try{
await wait(400);
ok('banner',/Horaire partagé/.test($('#banner-text').textContent));
ok('nav admin 11',$$('#nav button').length===11&&$$('#nav button').pop().id==='nav-nouveautes'&&!!$('#nav-comptes')&&!!$('#nav-modules')&&!!$('#nav-affectations')&&!$('#nav-presences'));
ok('board',$$('#main .week button.cc').length===41,$$('#main .week button.cc').length);
ok('exam card on board',$$('#main .cc.exam').length===1);
/* DND */
click($('#pick-g-302'));await wait(40);
ok('chip filter 302',$$('#main .week button.cc').length===20,$$('#main .week button.cc').length);
click($('#fm-e'));await wait(30);
ok('teacher chips',$$('.fchip').length===7,$$('.fchip').length);
click($('#fc-e-tremblay'));await wait(30);
ok('teacher filter',$$('#main .week button.cc').length===8,$$('#main .week button.cc').length);
click($('#fm-g'));await wait(30);
ok('back to all',$$('#main .week button.cc').length===41);
let src=$('.cc[data-key="c-mat-302_s11_2026-10-05"]');
ok('draggable',!!src&&src.dataset.drag==='1'&&!src.hasAttribute('draggable'));
const q=$('.cc[data-key="c-fra-302_s14_2026-10-05"]');q.scrollIntoView({block:'center'});await wait(30);const [qx,qy]=center(q);
ptr('pointerdown',qx,qy,q);ptr('pointermove',qx+9,qy+4);ptr('pointerup',qx+9,qy+4);await wait(40);
ok('quick release no freeze',!$('.drag-ghost')&&!$('.cc.dragging')&&$('#drawer').hidden&&!document.body.classList.contains('is-dragging'));
const cell=$('.wk-cell[data-date="2026-10-07"][data-grp="g-302"]');
let pt=await dragTo(src,cell,true);
ok('drop highlight',cell.classList.contains('drop-ok')&&!!$('.drag-ghost')&&src.classList.contains('dragging'));
ptr('pointerup',pt[0],pt[1]);await wait(40);
ok('drag cleaned',!$('.drag-ghost')&&!$('.cc.dragging')&&!document.body.classList.contains('is-dragging'));
ok('move dialog',/Déplacer un cours/.test($('#drawer').textContent)&&$('#drawer').classList.contains('dialog'));
ok('move warns',/Groupe 302 a déjà Français/.test($('#drawer').textContent));
const ts=$('#mv-time');ts.value='13:45-15:00';ts.dispatchEvent(new Event('change',{bubbles:true}));await wait(30);
ok('time change clears group warning',!/Groupe 302 a déjà/.test($('#drawer').textContent)||/Science/.test($('#drawer').textContent),$('#drawer .notice')&&$('#drawer .notice').textContent);
click($('[data-act=mv-apply]'));await wait(150);
let m=window.__store.get('cours/c-mat-302');
ok('moved once',m.annulees.includes('2026-10-05@s11')&&m.extras.some(x=>x.date==='2026-10-07'&&x.debut==='13:45'&&x.de==='2026-10-05@s11'),JSON.stringify(m.extras));
ok('moved chips',/Déplacé au mercredi 7/.test($('#main').textContent)&&/Déplacé ici/.test($('#main').textContent));
click($$('.toast button').pop());await wait(150);
m=window.__store.get('cours/c-mat-302');
ok('undo',m.annulees.length===0&&m.extras.length===0,JSON.stringify(m.annulees));
const a=$('.cc[data-key="c-sci-302_s12_2026-10-05"]'), bc=$('.cc[data-key="c-his-302_s13_2026-10-05"]');
pt=await dragTo(a,bc,false);ok('swap highlight',bc.classList.contains('drop-swap'));
ptr('pointerup',pt[0],pt[1]);await wait(40);
ok('swap dialog',/Échanger deux cours/.test($('#drawer').textContent));
click($('input[name=mv-scope][value=weekly]'));await wait(30);
click($('[data-act=mv-apply]'));await wait(150);
const sci=window.__store.get('cours/c-sci-302'), his=window.__store.get('cours/c-his-302');
ok('swap weekly',sci.creneaux.some(s=>s.id==='s12'&&s.au==='2026-10-04')&&sci.creneaux.some(s=>s.jour===1&&s.debut==='12:15'&&s.du==='2026-10-05')&&his.creneaux.some(s=>s.jour===1&&s.debut==='09:45'&&s.du==='2026-10-05'));
const titles=()=>[...$$('.wk-cell[data-grp="g-302"]')[0].querySelectorAll('.cc strong')].map(x=>{const k=x.querySelector('.cc-code');return k?x.textContent.slice(k.textContent.length).trim():x.textContent;});
ok('board after swap',titles()[1]==='Histoire du Québec et du Canada'&&titles()[2]==='Science et technologie',titles().join('|'));
click($('#w-prev'));await wait(50);
ok('past week unchanged',titles()[1]==='Science et technologie'&&titles()[2]==='Histoire du Québec et du Canada',titles().join('|'));
click($('#w-today'));await wait(50);
document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await wait(50);
ok('arrow key',/12 – 16 octobre/.test($('.wk-range').textContent),$('.wk-range').textContent);
click($('#w-today'));await wait(50);
click($('.cell-add[data-date="2026-10-06"][data-g="g-302"]'));await wait(40);
ok('add-at preset',$('#c-groupe')&&$('#c-groupe').value==='g-302'&&$('#c-j-0').value==='2',$('#c-d-0')&&$('#c-d-0').value);
click($('#dr-close'));await wait(30);
click($('.cc[data-key="c-fra-302_s14_2026-10-05"]'));await wait(40);
click($('[data-act=move-open]'));await wait(40);
ok('move from drawer',$('#drawer').classList.contains('dialog')&&!!$('#mv-day'));
const dsel=$('#mv-day');dsel.value='2026-10-09';dsel.dispatchEvent(new Event('change',{bubbles:true}));await wait(30);
click($('[data-act=mv-apply]'));await wait(150);
ok('moved via drawer',window.__store.get('cours/c-fra-302').extras.some(x=>x.date==='2026-10-09'));
click($('.cc[data-key="c-fra-302_s14_2026-10-05"]'));await wait(40);
ok('extras listed',/Changements ponctuels/.test($('#drawer').textContent));
click($('[data-act=x-extra]'));await wait(150);
ok('extra reverted',window.__store.get('cours/c-fra-302').extras.length===0&&window.__store.get('cours/c-fra-302').annulees.length===0);
click($('#dr-close'));await wait(30);
/* SIZE */
ok('expander shown',!!$('#exp-btn')&&$('#exp-btn').getAttribute('aria-expanded')==='true');
const metaVisible=()=>{const m=$('#main .week .cc-meta');return m&&getComputedStyle(m).display!=='none';};
ok('detailed meta visible',metaVisible());
const h1=$('#main .week').getBoundingClientRect().height;
click($('#exp-btn'));await wait(60);
ok('compact on',!!$('#main .week.compact')&&$('#exp-btn').getAttribute('aria-expanded')==='false');
ok('compact hides meta',!metaVisible());
await wait(400);
const h2=$('#main .week').getBoundingClientRect().height;
ok('compact smaller',h2<h1*0.75,Math.round(h1)+' -> '+Math.round(h2));
ok('compact moment',getComputedStyle($('#main .week .cc-time')).display!=='none'&&/^(Avant-midi|Après-midi|Toute la journée)$/.test($('#main .week .cc-time').textContent));
ok('status dot',!!$('#main .week .cc[data-st="done"]'));
document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'+',bubbles:true}));await wait(400);
ok('plus key expands',!$('#main .week.compact')&&metaVisible());
document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'-',bubbles:true}));await wait(60);
ok('minus key reduces',!!$('#main .week.compact'));
click($('[data-role=teacher]'));await wait(60);
ok('teacher compact kept',!!$('#main .week.compact')&&!!$('#exp-btn'));
click($('[data-role=admin]'));await wait(60);
click($('#exp-btn'));await wait(400);
ok('back to detailed',!$('#main .week.compact'));
// calendar course + attendance
click($('#pick-g-301'));await wait(40);
click($('#main .week button.cc:not(.exam)'));await wait(40);
ok('course drawer',!!$('#c-titre'));
click($('[data-act=goto-att]'));await wait(40);
ok('att drawer',$$('.att-list li').length===10);
click($('#dr-close'));await wait(30);
click($('#pick-g-301'));await wait(30);
// exam from board
click($('#main .cc.exam'));await wait(40);
ok('exam drawer',$('#x-titre')&&$('#x-titre').value==='Oral en anglais');
click($('#dr-close'));await wait(30);
// classes
click($('#nav-classes'));await wait(40);
ok('classes page',$$('.cl-row').length===2&&!!$('.cl-hd'));
click($('#cl-g-301'));await wait(80);click($('#fi-tab-cours'));await wait(60);
ok('class courses table',$$('select[data-assign]').length===6);
const sel=$('select[data-assign="c-mat-301"]');sel.value='e-roy';sel.dispatchEvent(new Event('change',{bubbles:true}));await wait(120);
ok('assign teacher',window.__store.get('cours/c-mat-301').enseignant==='e-roy');
// élèves
click($('#nav-eleves'));await wait(80);
ok('students table',$$('#main tbody tr').length===20,$$('#main tbody tr').length);
typeIn('#s-q','nath');await wait(40);
ok('search',$$('#main tbody tr').length===1&&/Nathan/.test($('#main tbody').textContent));
ok('search kept',$('#s-q').value==='nath');
click($('#main tbody .link'));await wait(80);
ok('student fiche + stats',!!$('.fiche')&&+(l=>{const d=[...document.querySelectorAll('.fh-stats>div')].find(x=>x.querySelector('dt').textContent===l);return d?d.querySelector('dd').textContent:'';})('Absences')>=5&&$('#drawer').hidden,(l=>{const d=[...document.querySelectorAll('.fh-stats>div')].find(x=>x.querySelector('dt').textContent===l);return d?d.querySelector('dd').textContent:'';})('Absences'));
ok('fiche nav with search',$('#fi-prev').disabled&&$('#fi-next').disabled&&/1 sur 1/.test($('.fiche-nav').textContent));
click($('#fi-edit'));await wait(60);
typeIn('#st-parent','Line Ouellet');$('#st-form').requestSubmit();await wait(120);
ok('student saved',window.__store.get('eleves/el-301-06').parent==='Line Ouellet'&&/Line Ouellet/.test($('#main').textContent));
click($('#fi-back'));await wait(80);
ok('back to list',!$('.fiche')&&$$('#main tbody tr').length===1&&$('#s-q').value==='nath');
// personnel
click($('#nav-personnel'));await wait(40);
ok('staff table',$$('#main tbody tr').length===8);
ok('private phone shown',/418 555-0110/.test($('#main').textContent));
{const tr=$('#main tr.row-link');click(tr&&tr.children[2]);}await wait(80);
ok('staff row click',!!$('.fiche')&&!!$('#fi-name'));
click($('#fi-back'));await wait(80);
click($('[data-act=new-staff]'));await wait(40);
typeIn('#sf-nom','Paul Gendron');typeIn('#sf-tel','418 555-0199');$('#sf-form').requestSubmit();await wait(150);
const pg=store().find(([k,v])=>k.startsWith('enseignants/')&&v.nom==='Paul Gendron');
ok('staff added',!!pg&&window.__store.get('dossiers-personnel/'+pg[0].split('/')[1]).telephone==='418 555-0199');
// présences (dans les classes)
click($('#nav-classes'));await wait(120);
ok('class att cards',$$('.cl-row').length===2&&/Présence/.test($('.cl-hd').textContent)&&!!$('#cl-g-301 .cl-rate')&&!$('.att-card')&&!!$('#pp-mois'));
click($('#pp-annee'));await wait(40);
ok('class att rate',/%/.test($('#cl-g-301 .cl-rate').textContent),$('#cl-g-301 .cl-rate').textContent);
click($('#cl-g-301'));await wait(100);
ok('class att table',$$('.fiche-tabs button').length===5&&$$('.st-row').some(r=>/Nathan Ouellet/.test(r.textContent))&&/Absences/.test($('.st-hd').textContent)&&$('#pp-annee').getAttribute('aria-pressed')==='true');
click($('#fi-tab-rattraper'));await wait(60);
ok('missing list',$$('[data-act=open-att]').length>=3,$$('[data-act=open-att]').length);
click($('[data-act=open-att]'));await wait(60);
ok('open missing att',$$('.att-list li').length===10);
click($('[data-act=att-all]'));await wait(20);click($('[data-act=att-save]'));await wait(150);
click($('#dr-close'));await wait(30);
click($('#fi-back'));await wait(60);
click($('#nav-personnel'));await wait(60);
click($('#pt-personnel'));await wait(40);
ok('staff att list',$$('.att-list li').length>=8,$$('.att-list li').length);
click($('#sd-0'));await wait(30);
click($('.att-list li [data-v=A]'));await wait(20);
click($('[data-act=sp-save]'));await wait(150);
const sp=Object.entries(window.__store.get('presences-personnel/'+$('#sd-0').dataset.date)?.statuts||{});
ok('staff att saved',sp.some(([k,v])=>v==='A'),JSON.stringify(sp).slice(0,90));
// examens
click($('#nav-examens'));await wait(40);
{const d=new Date(),td=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const nm=d.getHours()*60+d.getMinutes(),up=Math.min(25,[...window.__store].filter(([k,v])=>k.startsWith('examens/')&&!v.seance&&(v.date>td||(v.date===td&&(+String(v.debut).slice(0,2)*60+ +String(v.debut).slice(3,5))>nm))).length);
ok('exams upcoming',$$('#main [data-act=exam]').length===up,$$('#main [data-act=exam]').length+' / '+up);}
click($('[data-act=new-exam]'));await wait(40);
setSel('#x-cours','c-fra-301');$('#x-cours').dispatchEvent(new Event('input',{bubbles:true}));await wait(30);
typeIn('#x-date','2026-10-12');await wait(30);
$('#x-form').requestSubmit();await wait(40);
ok('exam on holiday refused',/Action de grâce/.test($('#drawer').textContent));
typeIn('#x-date','2026-10-13');await wait(30);
ok('exam times filled',$('#x-debut').value==='09:45',$('#x-debut').value);
$('#x-form').requestSubmit();await wait(150);
ok('exam created',store().some(([k,v])=>k.startsWith('examens/')&&v.cours==='c-fra-301'&&v.date==='2026-10-13'));
// calendrier scolaire
click($('#nav-annee'));await wait(40);
ok('year kpis',/Étape 1/.test($('#main').textContent)&&/Action de grâce/.test($('#main').textContent));
$('#p-enom').value='Test étape';$('#p-edu').value='2027-06-01';$('#p-eau').value='2027-06-10';$('#p-enom').closest('form').requestSubmit();await wait(150);
ok('etape added',window.__store.get('config/ecole').etapes.length===4);
// enseignant
click($('[data-role=teacher]'));await wait(60);
ok('teacher nav',$$('#nav button').length===6&&!!$('#nav-profil')&&!!$('#nav-mescours')&&!!$('#nav-dispos'));
ok('teacher board',$$('#main .week button.cc').length>0);
click($('#nav-examens'));await wait(40);
ok('teacher exams',$$('#main [data-act=exam]').length>=1||/Aucun examen/.test($('#main').textContent));
// élève
click($('[data-role=student]'));await wait(60);
ok('student exams panel',/Prochains examens/.test($('#main').textContent));
click($('#main .cc.exam')||$('#main [data-act=exam]'));await wait(40);
ok('student exam readonly',!$('#x-form')&&/Surveillance/.test($('#drawer').textContent));
click($('#dr-close'));await wait(30);
click($('#nav-annee'));await wait(30);
ok('student year no forms',!$('#p-enom'));
// clear
click($('[data-role=admin]'));await wait(60);
click($('#notices [data-act=clear-ex]'));await wait(30);
click($('[data-act=clear-ex-yes]'));await wait(1500);
const left=[...window.__store.values()].filter(v=>v.exemple).length;
ok('examples cleared',left===0,left);
ok('own kept',store().some(([k,v])=>v.nom==='Paul Gendron'));
}catch(e){R.push('ERROR '+e.message+' '+e.stack);}
R.push('ERRS '+JSON.stringify(window.__errs));
const pre=document.createElement('pre');pre.id='results';pre.textContent=R.join('\n');document.body.appendChild(pre);
})();
